In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.7.1+cu126


In [2]:
print("Hello I'am excited")

Hello I'am excited


In [3]:
##Introduction to Tensors
##Creating tensors


In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#Get tensor back as python int
scalar.item()

7

In [7]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
Tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
Tensor.ndim

3

In [16]:
Tensor.shape

torch.Size([1, 3, 3])

In [17]:
###Random tensors

###Random Tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and they adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers ->

In [18]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0171, 0.5565, 0.9481, 0.9721],
        [0.7609, 0.8986, 0.9493, 0.1089],
        [0.2820, 0.3946, 0.8965, 0.2175]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create  a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones


In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
### Creating a range of tensors and tensors-like
one_to_ten = torch.arange(0, 100, 2)
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [26]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big erroes you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [31]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1. Tensors not  right datatype-to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device


In [32]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9184, 0.3707, 0.6310, 0.1922],
        [0.2369, 0.4143, 0.8453, 0.3555],
        [0.4383, 0.3920, 0.7371, 0.7882]])

In [33]:
1 # Find out details about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9184, 0.3707, 0.6310, 0.1922],
        [0.2369, 0.4143, 0.8453, 0.3555],
        [0.4383, 0.3920, 0.7371, 0.7882]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)
Tensor operation include:
*Addition
*Subtraction
*Multiplication
*Division
*Matrix multiplication


In [34]:
#Create a tensor
tensor = torch.tensor([1,2,3])
tensor +100

tensor([101, 102, 103])

In [35]:
# Multiply tensor by 10
tensor *10


tensor([10, 20, 30])

In [36]:
# Subtraction 10
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out pytorch in-built functons
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning
1. Element multiplication
2. Matrix multiplication (dot product)


In [38]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [39]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [40]:
# Find the min
torch.min(x), x.min()


(tensor(1), tensor(1))

In [41]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [42]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32))

tensor(46.)

In [43]:
# Find the sum
torch.sum(x), x.sum()


(tensor(460), tensor(460))

## Find the positional min and max


In [44]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [45]:
# Find the position in tensor that has the  minimum value with argmin() -> returns index position of target where the minimum value occurs.
x.argmin()


tensor(0)

In [46]:
x[0]

tensor(1)

In [47]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [48]:
x[9]

tensor(91)

## Reshaping, Stacking, Squeezing and unsquezing tensors
* Reshaping-reshapes an input tensor to a defined shape
* view- Return a view of an input tensor of certain shape but keeps the same memory as the original tensor
* Stacking-combine multiple tensors on top of each other(vstack) or side by side(hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [49]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [50]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [53]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [54]:
# torch.squeeze()  - removes all single  dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
x_reshaped.shape

torch.Size([1, 9])

In [56]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [57]:
x_reshaped.squeeze().shape

torch.Size([9])

In [58]:
#torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [59]:
# torch.unsqueeze() - adds a single dimension to a  target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1) #Either dim 1 or 0
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [60]:
#torch.permute - rearrange the dimensions of a target tensor in a specified order
x = torch.randn(2, 3, 5)
x.size()
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 3])

In [61]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width ]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with Numpy.

In [62]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [63]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [64]:
# Lets index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [65]:
# Lets index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [66]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [67]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[: , :, 1]

tensor([[2, 5, 8]])

In [68]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [69]:
# Get index 0 of 0thand 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [70]:
# Index on x to return 9
print(x[0][2][2])

tensor(9)


In [71]:
# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor([[3, 6, 9]])


In [72]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## pytorch tensors & Numpy

Numpy is a popular scientific python numerical computing library.

And because of this, pytorch has fundamentally to interact with it.

* Data in NumPy, want in Pytorch tensor -> torch.from_numpy(ndarrray)
* PyTorch tensor -> Numpy -> torch.Tensor.numpy()

In [73]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflect numpy's default datatype of float64 unless specified otherwise
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [74]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [75]:
# Change the value of array, what will this do to 'tensor' ?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [76]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [77]:
# Change the tensor, what happens to numpy_tensor' ?
tensor = tensor +1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again .......

 To reduce the randomness in neural networks and PyTorch comes the concept of a random seed.

 Essentially what the random seed does is "flavour" the randomness.

In [78]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7525, 0.6833, 0.8097, 0.7399],
        [0.5023, 0.1588, 0.4372, 0.0210],
        [0.8020, 0.4293, 0.8285, 0.9783]])
tensor([[0.9710, 0.6690, 0.4831, 0.3601],
        [0.0956, 0.7330, 0.3607, 0.1771],
        [0.6610, 0.6659, 0.8870, 0.9917]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [79]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)


print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (option to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options...
3. Use cloud computing -GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

In [80]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [81]:
### 2. Check for GPU access with PyTorch

import torch
torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:....

E.g. run on GPU if available, else default to CPU

In [82]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [83]:
# Count number of devices
torch.cuda.device_count()

0

# 3. Putting tensors (and models) on the GPU.
### The reason we want out tensors/models on the GPU is because using a GPU results in faster computations.

In [84]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [85]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

### if tensor is on GPU, can't transform it to NumPy

In [86]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])